EPMLABSBRN-18 - data models were created
ElenaSpb/brn pull request #5
Opened 2019-09-27 09:18 UTC by goopnigoop

new entities were created:

- User
- Level
- ExerciseGroup:
- Exercise:
- StudyHistory

2019-09-27 11:13 UTC, epm-dev-priporov approved these changes
lgtm

2019-09-27 16:26 UTC, epm-dev-priporov requested changes
let's  add _Entity_ suffix  to the end of the each model  class
_ExerciseEntity_,  _LevelEntity_ etc

2019-09-29 17:24 UTC, ElenaSpb approved these changes

2019-10-05 06:40 UTC, ElenaSpb approved these changes

2019-10-05 06:40 UTC, merged